### ISSUE TITLE
cols required

### ISSUE THREAD

**Issue by juliaszusz** [arc85/celltalker#1]
Hi,

Thanks for building the tool and putting together such a detailed vignette. I am having some trouble at this step in the analysis:
**put.int <- putative_interactions(ligand.receptor.tibble=consistent.lig.recs,clusters=defined.clusters,groups=defined.groups,freq.group.in.cluster=0.05,ligands.and.receptors=interact.for)**

I then get the error:
`cols` is now required.
Please use `cols = c(lig.rec.exp)``cols` is now required.
Please use `cols = c(lig.rec.exp)`

I see that you fixed this issue for the function "unique_interactions", would there be a similar fix for the function "putative_interactions"?

Thank you,

Julia

**Comment by arc85** [comment]
Hi Julia, sorry for the trouble. I've recently created a new and simplified API, so I'm closing this comment.
