### ISSUE TITLE
Run celltalker with no replicate data

### ISSUE THREAD

**Issue by Jihong528** [arc85/celltalker#10]
Hi, Thanks for devloping celltalker!! I am a newer  to  use celltalker to find out the ligand and receptor in neuron cell type. 
But I don't have replicates and consistent.lig.recs seems to have nothing.
Code is pasted in below, could you please help me figure out the problem? Thanks a lot for your helping, I am just wondering how to run celltalker with no replicate data.

Also, I am wondering how to understand the parameter of   cells.reqd=10,freq.pos.reqd=0.5 in create_lig_rec_tib function.

```
defined.clusters <- ser.obj@meta.data$small_celltype
names(defined.clusters)<-colnames(ser.obj)
defined.groups <- ser.obj@meta.data$orig.ident
names(defined.groups)<-colnames(ser.obj)
defined.replicates <-  ser.obj@meta.data$orig.ident
names(defined.replicates)<-colnames(ser.obj)

reshaped.matrices <- reshape_matrices(count.matrix=expr.mat,
                                      clusters=defined.clusters,
                                      groups=defined.groups,
                                      replicates=defined.replicates,
                                      ligands.and.receptors=interact.for)

#Check out the hierarchy of the tibble
reshaped.matrices
unnest(reshaped.matrices,cols="samples")
names(pull(unnest(reshaped.matrices,cols="samples"))[[1]])

consistent.lig.recs <- create_lig_rec_tib(exp.tib=reshaped.matrices,
                                          clusters=defined.clusters,
                                          groups=defined.groups,
                                          replicates=defined.replicates,
                                          cells.reqd=10,
                                          freq.pos.reqd=0.5,
                                          ligands.and.receptors=interact.for)
```

This is the cellnumber
  GABA1 GABA2 GABA3 GABA4 GABA5 GABA6 Glu1 Glu2 Glu3
  WT       43    47    83   161    29    93   39   93   59
  ob/ob     4     6    19    25    17     2   10   10   17

I am wondering whether the cellnumber will affect the results or not.

Thanks a lot for your help.

**Comment by WangXiang50** [comment]
I Have the same issue with you. my data also do not have replicates. 
I tried to set the replicates as the same with groups. one group as one replicates, and it worked

**Comment by arc85** [comment]
Hi Jihong and WangXiang, sorry for the issues. I originally envisioned celltalker to work across replicate samples, but have recently built a new API that no longer has this reliance. Please check it out if you are still interested. Closing...
