### ISSUE TITLE
celltalk function notfound 

### ISSUE THREAD

**Issue by ZhijingJoe** [arc85/celltalker#18]
Hello arc85! I have installed celltalker v0.0.3.9000, and library celltalker, when run 
hca_bm_interactions <- celltalk(input_object=hca_bm,
  metadata_grouping="cell_types",
  ligand_receptor_pairs=ramilowski_pairs,
  number_cells_required=100,
  min_expression=1000,
  max_expression=20000,
  scramble_times=10)
It shows   Error in celltalk(input_object = seu, metadata_grouping = "cell_types",  : 
  could not find function "celltalk". Is there anything wrong with this code? Or the celltalker version?

**Comment by arc85** [comment]
Hi chilijuido23, thanks for checking out celltalker! Yes, the version needs to be 0.0.5.9000 to use the celltalk function. Try installing with remotes:

> remotes::install_github("arc85/celltalker@v0.0.5.9000")
