### ISSUE TITLE
question  for output the interactions

### ISSUE THREAD

**Issue by MMriran** [arc85/celltalker#2]
Hi,

    Thanks for building the tool and putting together such a detailed vignette.  I had run the code as introduced in your workflow and got the cell-cell interaction plots. Then how can I got the a dataframe that included the detailed information of cell-cell interaction so that I can output the results as a table？

Thank you,
MMrian

**Comment by aanchalsharma833** [comment]
Hi MMriran,

I was also stuck with this question and tried following:
for.circos.pbmc is the object (list) with all the interactions to be plotted by Circos_plot function in cellTalker.

to view this list:
`
for.circos.pbmc
`

to convert above list to a data frame and write into a file:
`for.circos.pbmc.df<-data.frame(t(sapply(for.circos.pbmc,c)))`
`sink("cellTalker_output.txt")`
`print(for.circos.pbmc.df)`
`sink()`

hope this helps!

**Comment by arc85** [comment]
Thanks MMriran! Closing this with the advent of a new API.
