### ISSUE TITLE
celltalk function not found

### ISSUE THREAD

**Issue by BohrXD** [arc85/celltalker#24]
while using  reshape_matrices()
got: could not find function "reshape_matrices"
Does my celltalker version wrong?

**Comment by BohrXD** [comment]
I found the reshape_matrices() function in the history version v0.0.1.9000
so:
remotes::install_github("arc85/celltalker@v0.0.5.9000"）
works

**Comment by BohrXD** [comment]
I found the reshape_matrices() function in the history version v0.0.1.9000
so:
remotes::install_github("arc85/celltalker@v0.0.1.9000"）
works

**Comment by UboCA** [comment]
> I found the reshape_matrices() function in the history version v0.0.1.9000 so: remotes::install_github("arc85/celltalker@v0.0.1.9000"） works

Hi, is all OK there after altering version into **celltalker@v0.0.1.9000**? 
I ask it as I got error when I run create_lig_rec_tib :

```{r}
consistent.lig.recs <- create_lig_rec_tib(exp.tib=reshaped.matrices,
                                          clusters=defined.clusters,
                                          groups=defined.groups,
                                          replicates=defined.replicates,
                                          cells.reqd=10,
                                          freq.pos.reqd=0.5,
                                          ligands.and.receptors=interact.for)
```
```
Error in `select()`:
! <text>:1:7: unexpected symbol
1: Using an
          ^
Backtrace:
 1. celltalker::create_lig_rec_tib(...)
 2. base::lapply(cluster.pos, function(x) select(x, -cols.to.drop))
 3. celltalker (local) FUN(X[[i]], ...)
 5. dplyr:::select.data.frame(x, -cols.to.drop)
 ```

**Comment by PengBingming** [comment]
I get the same error,  can anyone help us.

**Comment by arc85** [comment]
Apologies for the errors! The v0.0.1.9000 version of celltalker has been superseded by the current version (v0.0.7.9000). Please check out the new version.
