### ISSUE TITLE
Highlight Unique among Common

### ISSUE THREAD

**Issue by XiaofeiSunUCSF** [arc85/celltalker#6]
Hi,
I read your paper published in Immunity.
I wondered how did you draw the circos_plot highlighting unique lines among common lines (as shown in Figure 6)
Thanks for your help!

Xiaofei

**Comment by arc85** [comment]
I had used the same code for drawing the circos links, but subset by unique and shared interactions. I would now recommend running celltalk on two sets of samples and comparing the strengths of the inferred interactions, then drawing two circos plots to highlight significant differences.
