### ISSUE TITLE
Error in x[z, ] : subscript out of bounds

### ISSUE THREAD

**Issue by zochzh** [arc85/celltalker#7]
Hello, team celltalker!

Thank you for developing this wonderful R package.

I have data from 20 single cell samples that have been processed by [seurat](https://github.com/satijalab/seurat). I ran the code according to your tutorial, and it worked fine until I got to this point.

**consistent.lig.recs <- create_lig_rec_tib(exp.tib=reshaped.matrices, clusters=defined.clusters, groups=defined.groups, replicates=defined.replicates, cells.reqd=10, freq.pos.reqd=0.2, ligands.and.receptors=interact.for)**

And I got the following error message:

**Error in x[z, ] : subscript out of bounds.**

I tried searching for an answer on Google, but it didn't solve my problem.
I hope to get your reply.Thank you very much。

Attach some sample information.I hope it helps.Thanks again to your team.

# A tibble: 20 x 3
   group sample expr.matrices
   <chr> <chr>  <list>
 1 OM    CAT6   <named list [4]>
 2 OM    NPDR1  <named list [4]>
 3 OM    PCV3   <named list [4]>
 4 OM    PCV5   <named list [4]>
 5 OM    WAMD1  <named list [4]>
 6 OW    CAT1   <named list [4]>
 7 OW    CAT3   <named list [3]>
 8 OW    CAT7   <named list [3]>
 9 OW    DME2   <named list [4]>
10 OW    PCV1   <named list [4]>
11 YM    HH4    <named list [4]>
12 YM    HH5    <named list [4]>
13 YM    UN3    <named list [4]>
14 YM    UN5    <named list [4]>
15 YM    UN6    <named list [4]>
16 YW    HH3    <named list [4]>
17 YW    HH6    <named list [4]>
18 YW    HH7    <named list [4]>
19 YW    HH8    <named list [4]>
20 YW    UN4    <named list [4]>

**Comment by mieko-cc** [comment]
I have the same question, could you please give us a help? 
Thank you so much!
@arc85

**Comment by mieko-cc** [comment]
@zochzh Do you find some resolution?

**Comment by zochzh** [comment]
> @zochzh Do you find some resolution?
Sorry, I could't find a way either, sad!

**Comment by mdwahiduzzaman2019** [comment]
Hello Celltalker team,
I ran the following command on the R . 
 consistent.lig.recs <- create_lig_rec_tib(exp.tib=reshaped.matrices, clusters=defined.clusters, groups=defined.groups, replicates=defined.replicates, cells.reqd=10, freq.pos.reqd=05, ligands.and.receptors=interact.for) 

After running that I got a message that I will note here, 
Error in x[z, ] : subscript out of bounds


I checked it several times from Google. But I didn't get any solution yet. Could anyone help me? 
Thanks you.

**Comment by hartlama** [comment]
Also having this issue when running the tutorial. 

traceback() produces:

4: FUN(X[[i]], ...)
3: lapply(pid.cell.num, function(x) x[z, ])
2: Reduce(rbind, lapply(pid.cell.num, function(x) x[z, ]))
1: create_lig_rec_tib(exp.tib = reshaped.matrices, clusters = defined.clusters, 
       groups = defined.groups, replicates = defined.replicates, 
       cells.reqd = 10, freq.pos.reqd = 0.5, ligands.and.receptors = interact.for)

**Comment by 1185958508** [comment]
> Hello, team celltalker!
> 
> Thank you for developing this wonderful R package.
> 
> I have data from 20 single cell samples that have been processed by [seurat](https://github.com/satijalab/seurat). I ran the code according to your tutorial, and it worked fine until I got to this point.
> 
> **consistent.lig.recs <- create_lig_rec_tib(exp.tib=reshaped.matrices, clusters=defined.clusters, groups=defined.groups, replicates=defined.replicates, cells.reqd=10, freq.pos.reqd=0.2, ligands.and.receptors=interact.for)**
> 
> And I got the following error message:
> 
> **Error in x[z, ] : subscript out of bounds.**
> 
> I tried searching for an answer on Google, but it didn't solve my problem.
> I hope to get your reply.Thank you very much。
> 
> Attach some sample information.I hope it helps.Thanks again to your team.
> 
> # A tibble: 20 x 3
> group sample expr.matrices
> 
> 1 OM CAT6 <named list [4]>
> 2 OM NPDR1 <named list [4]>
> 3 OM PCV3 <named list [4]>
> 4 OM PCV5 <named list [4]>
> 5 OM WAMD1 <named list [4]>
> 6 OW CAT1 <named list [4]>
> 7 OW CAT3 <named list [3]>
> 8 OW CAT7 <named list [3]>
> 9 OW DME2 <named list [4]>
> 10 OW PCV1 <named list [4]>
> 11 YM HH4 <named list [4]>
> 12 YM HH5 <named list [4]>
> 13 YM UN3 <named list [4]>
> 14 YM UN5 <named list [4]>
> 15 YM UN6 <named list [4]>
> 16 YW HH3 <named list [4]>
> 17 YW HH6 <named list [4]>
> 18 YW HH7 <named list [4]>
> 19 YW HH8 <named list [4]>
> 20 YW UN4 <named list [4]>

Hi,
Do you find some resolution now?

**Comment by WangXiang50** [comment]
I  also have the same issue.

**Comment by bluedominion** [comment]
If you take a look at the "Help" info for the create_lig_rec_tib command, there are some hints of what is going on in there.  Basically when you run reshape_matrices, you need to feed in your groups/clusters/replicates as factors, instead of as character lists.  It's kind of an ugly omission in the tutorial.  If you replace the current reshaped.matrices command with:

`reshaped.matrices <- reshape_matrices(count.matrix=expr.mat,clusters=as.factor(defined.clusters),groups=as.factor(defined.groups),replicates=as.factor(defined.replicates),ligands.and.receptors=interact.for)`

It should work from there.  Or at least it did for me!  The steps after that...ehhh...might just be my own data.

**Comment by arc85** [comment]
Hi everyone... sorry for the issues! I have now simplified the API, so closing this thread.
