### ISSUE TITLE
How to cite this great software in paper?

### ISSUE THREAD

**Issue by grimwoo** [arc85/celltalker#8]
Hi, thanks for developing this great software. I wonder if authors of celltalker had published the paper that can be cited ?

**Comment by grimwoo** [comment]
@arc85

**Comment by arc85** [comment]
Hi grimwoo, sorry for not getting back to you sooner! I doubt this is still relevant, but if anyone else comes across this pls cite our immunity paper: https://pubmed.ncbi.nlm.nih.gov/31924475/
